import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cookies } from "next/headers";

//components
import AppSidebar from "@/components/ui/nav-section/app-sidebar";
import Navbar from "@/components/ui/nav-section/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import WrapperProvider from "@/components/providers/provider-wraper";


export default async function RootLayout({ children }) {

  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true';

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased`}
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
         >
          <WrapperProvider cookieState={defaultOpen}>
         
              <AppSidebar />

              <main className="w-full">
                  {/* Sticky Navbar */}
                <div className="sticky bg-background top-0 z-50">
                    <Navbar />
                </div>
            
                <div className="flex-1 overflow-y-auto">
                  <div className="px-4 py-4"> {/* Added py-4 for spacing */}
                    {children}
                  </div>
                </div>

              </main>

            </WrapperProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
